//nodes to location mapping
const locationNames = {
  1: "Main Gate",
  2: "Administration Block",
  3: "Director's Office",
  4: "Academic Block A",
  5: "Academic Block B",
  6: "Computer Center",
  7: "Library",
  8: "Workshop Area",
  9: "Electrical Department",
  10: "Mechanical Department",
  11: "Civil Department",
  12: "Architecture Department",
  13: "Chemistry Department",
  14: "Physics Department",
  15: "Central Auditorium",
  16: "Student Activity Center",
  17: "Sports Complex",
  18: "Basketball Court",
  19: "Volleyball Court",
  20: "Tennis Court",
  21: "Cafeteria",
  22: "Guest House",
  23: "Health Center",
  24: "Post Office",
  25: "Bank",
  26: "ATM",
  27: "Shopping Complex",
  28: "Faculty Housing A",
  29: "Faculty Housing B",
  30: "Faculty Housing C",
  31: "Boys Hostel A",
  32: "Boys Hostel B",
  33: "Boys Hostel C",
  34: "Girls Hostel A",
  35: "Girls Hostel B",
  36: "Research Center",
  37: "Innovation Center",
  38: "Incubation Center",
  39: "Parking Area A",
  40: "Parking Area B",
  41: "Main Garden",
  42: "Zen Garden",
  43: "Amphitheater",
  44: "Open Air Theater",
  45: "Solar Panel Area",
  46: "Water Treatment Plant",
  47: "Electrical Substation",
  48: "Security Office",
  49: "Maintenance Office",
  50: "Transport Office",
  51: "Cycle Stand",
  52: "Bus Stand",
  53: "Main Road Junction",
  54: "North Gate",
  55: "East Gate",
  56: "West Gate",
  57: "South Gate",
  58: "Footpath Junction A",
  59: "Footpath Junction B",
  60: "Footpath Junction C",
  61: "Footpath Junction D",
  62: "Pedestrian Bridge",
  63: "Emergency Exit",
  64: "Back Gate"
};